"use client";
import { useEffect, useMemo, useState } from "react";

type Car={id:string;year:number;make:string;model:string;trim:string;price:number;monthly:number;miles:number;fuel:string;image:string;source:string;location:string;distance:number;badge:string;accent:string};
const CARS:Car[]=[
{id:"taycan",year:2024,make:"Porsche",model:"Taycan",trim:"4S",price:89980,monthly:1184,miles:6200,fuel:"Electric",source:"Auto.dev",location:"Manhattan, NY",distance:4,badge:"Great price",accent:"#e6ff57",image:"https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1400&q=88"},
{id:"defender",year:2023,make:"Land Rover",model:"Defender",trim:"110 X-Dynamic",price:71640,monthly:947,miles:18400,fuel:"Gas",source:"MarketCheck",location:"Brooklyn, NY",distance:9,badge:"$4,200 below market",accent:"#e07b5c",image:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=88"},
{id:"bmw",year:2024,make:"BMW",model:"i4",trim:"eDrive40",price:54750,monthly:689,miles:4100,fuel:"Electric",source:"Lease partner",location:"Jersey City, NJ",distance:11,badge:"Lease takeover",accent:"#73a9ff",image:"https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1400&q=88"},
{id:"audi",year:2023,make:"Audi",model:"RS e-tron GT",trim:"Quattro",price:82900,monthly:1068,miles:11320,fuel:"Electric",source:"MarketCheck",location:"Great Neck, NY",distance:18,badge:"Rare spec",accent:"#ff776b",image:"https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1400&q=88"},
{id:"bronco",year:2024,make:"Ford",model:"Bronco",trim:"Wildtrak",price:63995,monthly:821,miles:890,fuel:"Gas",source:"Auto.dev",location:"Stamford, CT",distance:31,badge:"Almost new",accent:"#f0b44d",image:"https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=88"},
{id:"volvo",year:2024,make:"Volvo",model:"XC90",trim:"Recharge",price:68420,monthly:889,miles:7250,fuel:"Hybrid",source:"MarketCheck",location:"White Plains, NY",distance:26,badge:"CPO",accent:"#8cbab4",image:"https://images.unsplash.com/photo-1494905998402-395d579af36f?auto=format&fit=crop&w=1400&q=88"}];
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);

export default function CarMarketplace(){
const[query,setQuery]=useState("");const[fuel,setFuel]=useState("All");const[sort,setSort]=useState("recommended");const[favs,setFavs]=useState<string[]>([]);const[compare,setCompare]=useState<string[]>([]);const[selected,setSelected]=useState<Car|null>(null);const[loading,setLoading]=useState(true);const[menu,setMenu]=useState(false);const[inventory,setInventory]=useState<Car[]>(CARS);const[dataMode,setDataMode]=useState<"demo"|"live">("demo");
useEffect(()=>{const t=setTimeout(()=>setLoading(false),850);return()=>clearTimeout(t)},[]);useEffect(()=>{try{setFavs(JSON.parse(localStorage.getItem("nesed-favorites")||"[]"))}catch{}},[]);useEffect(()=>localStorage.setItem("nesed-favorites",JSON.stringify(favs)),[favs]);
useEffect(()=>{fetch("/api/vehicles?zip=10001&limit=18").then(r=>r.json()).then(({data,mode})=>{if(mode==="live"&&Array.isArray(data)&&data.length){setInventory(data.map((x:any,i:number)=>({id:x.id||`live-${i}`,year:x.year||0,make:x.make||"Vehicle",model:x.model||"Listing",trim:x.trim||"",price:Number(x.price)||0,monthly:Math.round((Number(x.price)||0)*.014),miles:Number(x.miles)||0,fuel:x.fuel||"Other",image:x.image||CARS[i%CARS.length].image,source:x.source||"Provider",location:x.location||"Local dealer",distance:Number(x.distance)||0,badge:"Live listing",accent:CARS[i%CARS.length].accent})));setDataMode("live")}}).catch(()=>{})},[]);
const cars=useMemo(()=>{let x=inventory.filter(c=>`${c.year} ${c.make} ${c.model} ${c.fuel}`.toLowerCase().includes(query.toLowerCase())&&(fuel==="All"||c.fuel===fuel));if(sort==="price")x=[...x].sort((a,b)=>a.price-b.price);if(sort==="monthly")x=[...x].sort((a,b)=>a.monthly-b.monthly);if(sort==="miles")x=[...x].sort((a,b)=>a.miles-b.miles);return x},[query,fuel,sort,inventory]);
const fav=(id:string)=>setFavs(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]);const comp=(id:string)=>setCompare(x=>x.includes(id)?x.filter(i=>i!==id):x.length<3?[...x,id]:x);
return <><div className={`intro ${loading?"":"intro-out"}`}><div className="intro-orbit"><div/></div><div className="intro-word"><span className="brand-dot"/>NESED</div><p>BRINGING THE MARKET INTO FOCUS</p><i/></div>
<header className="nav-shell"><a className="brand" href="#top"><span className="brand-dot"/>NESED</a><nav className={menu?"open":""}><a href="#inventory">Inventory</a><a href="#how">How it works</a><a href="#providers">Data partners</a></nav><div className="nav-actions"><button className="save">Saved <b>{favs.length}</b></button><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?"×":"☰"}</button></div></header>
<main id="top"><section className="hero"><div className="hero-copy"><div className="kicker"><span/>ONE SEARCH. THE WHOLE MARKET.</div><h1>Find the car.<br/><em>Keep your edge.</em></h1><p className="lede">Live purchase and lease offers, normalized into one calm, intelligent view. No tab chaos. No mystery math.</p><div className="search"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “electric SUV under $70k”" aria-label="Search vehicles"/></label><button onClick={()=>document.getElementById("inventory")?.scrollIntoView()}>Search market <span>↗</span></button></div><div className="suggestions"><span>Popular</span>{["Porsche Taycan","Electric","Lease takeover"].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div></div><div className="hero-visual"><img src={CARS[0].image} alt="Luxury electric car"/><div className="wash"/><div className="signal"><i/><div><small>MARKET SIGNAL</small><b>Prices down 3.8%</b><p>Luxury EVs · 30 days</p></div></div><div className="index">01 <i/> 06</div></div></section>
<section className="proof" id="providers"><p>One clean feed, powered by</p><div><b>MarketCheck</b><b>auto.dev</b><b>NHTSA</b><b>Lease partners</b></div><span>Updated every search</span></section>
<section className="inventory" id="inventory"><div className="section-head"><div><span className="eyebrow">CURATED NEAR NEW YORK</span><h2>Worth a closer look.</h2></div><p>Every listing is normalized, deduplicated and ranked around value—not ad spend.</p></div><div className="toolbar"><div>{["All","Electric","Hybrid","Gas"].map(x=><button className={fuel===x?"active":""} onClick={()=>setFuel(x)} key={x}>{x}</button>)}</div><aside><span>{cars.length} matches</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Recommended</option><option value="price">Lowest price</option><option value="monthly">Lowest monthly</option><option value="miles">Lowest mileage</option></select></aside></div><div className="car-grid">{cars.map((car,i)=><article className="car-card" key={car.id} style={{"--accent":car.accent} as React.CSSProperties}><div className="car-image" onClick={()=>setSelected(car)}><img src={car.image} alt={`${car.make} ${car.model}`}/><i/><span className="badge">{car.badge}</span><button className={`heart ${favs.includes(car.id)?"on":""}`} onClick={e=>{e.stopPropagation();fav(car.id)}}>{favs.includes(car.id)?"♥":"♡"}</button><small>0{i+1}</small></div><div className="car-info" onClick={()=>setSelected(car)}><div><small>{car.year} · {car.trim}</small><h3>{car.make} {car.model}</h3></div><div><b>{money(car.price)}</b><span>{money(car.monthly)}/mo est.</span></div></div><div className="meta"><span>{car.miles.toLocaleString()} mi</span><span>{car.fuel}</span><span>{car.distance} mi away</span></div><footer><span>via <b>{car.source}</b></span><button className={compare.includes(car.id)?"selected":""} onClick={()=>comp(car.id)}>{compare.includes(car.id)?"Added":"+ Compare"}</button></footer></article>)}</div>{!cars.length&&<div className="empty"><span>⌕</span><h3>No exact matches—yet.</h3><p>Try removing a filter or searching by make or fuel type.</p><button onClick={()=>{setFuel("All");setQuery("")}}>Reset search</button></div>}</section>
<section className="method" id="how"><div><span className="eyebrow">THE NESED DIFFERENCE</span><h2>Less hunting.<br/>More knowing.</h2><p>We turn fragmented inventory into a decision-ready shortlist—so the best deal is obvious before you ever contact a seller.</p><a href="#inventory">Explore the market ↗</a></div><div className="method-grid">{[["01","Aggregate","Purchase and lease inventory from approved data providers."],["02","Normalize","One format for prices, mileage, incentives and seller data."],["03","Rank","Value signals surface the offers that genuinely stand out."],["04","Verify","VIN and recall details can be checked against NHTSA."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="cta"><div><span className="eyebrow">YOUR NEXT CAR IS ALREADY OUT THERE</span><h2>Search less.<br/><em>Drive sooner.</em></h2></div><a href="#top">Start a new search ↗</a></section></main>
<footer className="site-footer"><a className="brand" href="#top"><span className="brand-dot"/>NESED</a><p>Every car. Every lease. One search.</p><span>© 2026 NESED · {dataMode==="live"?"Live provider inventory":"Demo inventory until API keys are connected"}</span></footer>
{compare.length>0&&<div className="compare"><span><b>{compare.length}</b> selected</span><div>{compare.map(id=><small key={id}>{CARS.find(c=>c.id===id)?.model}<button onClick={()=>comp(id)}>×</button></small>)}</div><button disabled={compare.length<2}>Compare now</button></div>}
{selected&&<div className="backdrop" onClick={()=>setSelected(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><img src={selected.image} alt={`${selected.make} ${selected.model}`}/><div className="drawer-body"><span className="eyebrow">{selected.badge.toUpperCase()}</span><h2>{selected.year} {selected.make}<br/>{selected.model}</h2><p>{selected.trim} · {selected.fuel} · {selected.miles.toLocaleString()} miles</p><div className="drawer-price"><b>{money(selected.price)}</b><span>{money(selected.monthly)}/month estimated</span></div><div className="facts"><div><small>LOCATION</small><b>{selected.location}</b></div><div><small>SOURCE</small><b>{selected.source}</b></div><div><small>DISTANCE</small><b>{selected.distance} miles</b></div><div><small>DATA STATUS</small><b className="verified">● Ready to verify</b></div></div><a className="primary" href="#providers">View provider offer ↗</a><p className="disclaimer">Demo inventory. Connect a supported API key to display live dealer links and availability.</p></div></aside></div>}</>}
